# Generated by Django 4.1.1 on 2023-01-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(default=1)),
                ("nonce", models.IntegerField(default=1)),
                ("merkle_root_hash", models.CharField(default="0", max_length=1000)),
                ("prev_hash", models.CharField(default="0", max_length=1000)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locId",
                    models.CharField(
                        default="LOC29630", editable=False, max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(default="Name", max_length=100)),
                ("location", models.CharField(default="Location", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mempool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.CharField(default="", max_length=250)),
                ("data", models.CharField(default="", max_length=250)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="TxnDB2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.CharField(default="", max_length=250)),
                ("data", models.CharField(default="", max_length=250)),
                ("timestamp", models.DateTimeField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_txnDB2",
                        to="sensor_app.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TxnDB1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.CharField(default="", max_length=250)),
                ("data", models.CharField(default="", max_length=250)),
                ("timestamp", models.DateTimeField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_txnDB1",
                        to="sensor_app.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn", models.CharField(default="", max_length=250)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_transactions",
                        to="sensor_app.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sensor_id", models.CharField(max_length=100, unique=True)),
                ("unit", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="sensor_app.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sensors",
                        to="sensor_app.sensor",
                    ),
                ),
            ],
        ),
    ]
